import os
import io
import json
from fastapi import APIRouter, Depends, HTTPException, status, Response
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from typing import List, Any
from backend.app.database.connection import get_db
from backend.app.models.schemas import User, Paper, Report, ReportResponse, ReportGenerateRequest, UserSetting
from backend.app.api.endpoints.auth import get_current_user
from backend.app.rag.agents import SYSTEM_PROMPTS, call_llm_stream

router = APIRouter()

@router.post("/generate", response_model=ReportResponse)
def generate_report(
    req: ReportGenerateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> Any:
    # 1. Fetch papers
    papers = db.query(Paper).filter(Paper.id.in_(req.paper_ids), Paper.user_id == current_user.id).all()
    if not papers:
        raise HTTPException(status_code=404, detail="No matching papers found")
        
    # 2. Build prompt context
    papers_context = ""
    for idx, p in enumerate(papers):
        # Extract abstract and metadata
        p_meta = json.loads(p.metadata_json) if p.metadata_json else {}
        papers_context += f"--- Paper {idx+1}: {p.title} ---\nAuthors: {p.authors}\nAbstract: {p.abstract}\nReferences: {p_meta.get('references', '')[:1000]}\n\n"
        
    # 3. Determine agent type & system prompt
    agent_type = req.type  # review, summary, gap, presentation, bibtex
    system_prompt = SYSTEM_PROMPTS.get(agent_type, SYSTEM_PROMPTS["coordinator"])
    
    # Override/append custom instructions if provided
    user_prompt = f"Perform analysis and generate the report. Papers detail:\n\n{papers_context}"
    if req.custom_prompt:
        user_prompt += f"\nCustom User Instructions: {req.custom_prompt}"
        
    # 4. Generate report content
    user_setting = db.query(UserSetting).filter(UserSetting.user_id == current_user.id).first()
    if not user_setting:
        user_setting = UserSetting(user_id=current_user.id)
        
    generator = call_llm_stream(
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        chat_history=[],
        settings_obj=user_setting
    )
    report_content = "".join(list(generator))
    
    # 5. Save report to DB
    title = f"Generated {req.type.capitalize()} - {papers[0].title[:30]}"
    if len(papers) > 1:
        title += f" & {len(papers)-1} others"
        
    report = Report(
        user_id=current_user.id,
        type=req.type,
        title=title,
        content=report_content
    )
    db.add(report)
    db.commit()
    db.refresh(report)
    
    return report

@router.get("/", response_model=List[ReportResponse])
def get_reports(db: Session = Depends(get_db), current_user: User = Depends(get_current_user)) -> Any:
    return db.query(Report).filter(Report.user_id == current_user.id).order_by(Report.created_at.desc()).all()

@router.delete("/{report_id}")
def delete_report(report_id: int, db: Session = Depends(get_db), current_user: User = Depends(get_current_user)) -> Any:
    report = db.query(Report).filter(Report.id == report_id, Report.user_id == current_user.id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    db.delete(report)
    db.commit()
    return {"message": "Report deleted successfully"}

@router.get("/{report_id}/export/{format}")
def export_report(
    report_id: int,
    format: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> Any:
    report = db.query(Report).filter(Report.id == report_id, Report.user_id == current_user.id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
        
    format = format.lower()
    filename_base = f"report_{report.id}"
    
    if format == "markdown":
        headers = {"Content-Disposition": f"attachment; filename={filename_base}.md"}
        return Response(content=report.content, media_type="text/markdown", headers=headers)
        
    elif format == "html":
        # Wrap markdown in simple HTML structure with Tailwind CSS CDN for quick pretty styling
        html_content = f"""<!DOCTYPE html>
<html>
<head>
    <title>{report.title}</title>
    <meta charset="utf-8">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50 text-gray-900 py-12 px-6 max-w-4xl mx-auto">
    <h1 class="text-3xl font-bold mb-2 text-indigo-700 border-b pb-4">{report.title}</h1>
    <p class="text-sm text-gray-500 mb-8">Generated by ResearchMind on {report.created_at.strftime('%Y-%m-%d %H:%M')}</p>
    <article class="prose max-w-none whitespace-pre-wrap leading-relaxed">{report.content}</article>
</body>
</html>
"""
        headers = {"Content-Disposition": f"attachment; filename={filename_base}.html"}
        return Response(content=html_content, media_type="text/html", headers=headers)
        
    elif format == "bibtex":
        headers = {"Content-Disposition": f"attachment; filename={filename_base}.bib"}
        return Response(content=report.content, media_type="text/plain", headers=headers)
        
    elif format == "pdf":
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.colors import HexColor
            
            buffer = io.BytesIO()
            doc = SimpleDocTemplate(
                buffer, 
                pagesize=letter,
                rightMargin=54, leftMargin=54, topMargin=54, bottomMargin=54
            )
            
            styles = getSampleStyleSheet()
            
            # Custom styled ParagraphStyles
            title_style = ParagraphStyle(
                'ReportTitle',
                parent=styles['Heading1'],
                fontSize=22,
                textColor=HexColor('#4F46E5'),  # Indigo
                spaceAfter=15
            )
            meta_style = ParagraphStyle(
                'ReportMeta',
                parent=styles['Normal'],
                fontSize=9,
                textColor=HexColor('#6B7280'),  # Gray
                spaceAfter=25
            )
            body_style = ParagraphStyle(
                'ReportBody',
                parent=styles['Normal'],
                fontSize=11,
                leading=16,
                textColor=HexColor('#1F2937'),  # Slate
                spaceAfter=10
            )
            
            story = []
            story.append(Paragraph(report.title, title_style))
            story.append(Paragraph(f"Generated by ResearchMind on {report.created_at.strftime('%Y-%m-%d %H:%M')}", meta_style))
            
            # Simple line-break to paragraph logic for PDF layout
            paragraphs = report.content.split("\n\n")
            for p in paragraphs:
                if p.strip():
                    # Replace markdown headings with bold/underlines if needed
                    text = p.strip()
                    if text.startswith("###"):
                        text = f"<b>{text.replace('###', '').strip()}</b>"
                    elif text.startswith("##"):
                        text = f"<font size='14'><b>{text.replace('##', '').strip()}</b></font>"
                    elif text.startswith("#"):
                        text = f"<font size='16'><b>{text.replace('#', '').strip()}</b></font>"
                        
                    # Handle basic bold replacements
                    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
                    text = text.replace("\n", "<br/>")
                    
                    try:
                        story.append(Paragraph(text, body_style))
                    except Exception:
                        # Fallback if XML-like tags error out
                        story.append(Paragraph(p.strip().replace("\n", "<br/>"), body_style))
                    story.append(Spacer(1, 10))
                    
            doc.build(story)
            buffer.seek(0)
            
            headers = {"Content-Disposition": f"attachment; filename={filename_base}.pdf"}
            return StreamingResponse(buffer, media_type="application/pdf", headers=headers)
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"PDF Generation Failed: {str(e)}")
            
    else:
        raise HTTPException(status_code=400, detail=f"Unsupported format: {format}")
